name: Go

on:
  schedule:
    - cron: '0 0 * * *' # each 12:00 UTC
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ] # semver release
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: 'true'

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'

    - name: Generate xrpc support code
      run: make xrpc

    - name: Build
      run: make feed

